Dimuthu ingester
Malintha1996/datasearch-dengue-store pull request #10
Opened 2020-07-24 16:43 UTC by DimuthuMadushan

2020-07-24 18:23 UTC, Malintha1996 commented on d
> +[1mindex c21d1bd..e85e76c 100644[m
Remove this file from the commit

2020-07-24 18:26 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/RequestHandler.java
> +import io.datasearch.denguestore.ingestion.DataIngester;
package name should be io.datasearch.disesedata.ingestion.DataStore

2020-07-24 18:27 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/DengDIPipeLine.java
> +import io.datasearch.denguestore.ingestion.DataIngester;
Same here

2020-07-24 18:29 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/DengDIPipeLine.java
> +import io.datasearch.denguestore.ingestion.DataIngester;
pakage name should be io.datasearch.disesedata.*

2020-07-24 18:30 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/FeatureData.java
> +package io.datasearch.denguestore.data;
Why do we need the FeatureData class

2020-07-24 18:35 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/FeatureData.java
> +    public void buildQueries(List<Map<String, String>> queriesList) {
This method is not required?

2020-07-24 18:36 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/FeatureData.java
> +    public Filter getSubsetFilter() {
This is not required for the purpose of this class right?

2020-07-24 18:39 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/DiseaseData.java
> +package io.datasearch.denguestore.data;
package name shoud be compying with the file path
it should be like` io.datasearch.diseasedata.store.dengdipipeline.ingestion.data`
We can remove the` data` part as well. Look into this

2020-07-24 18:39 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/DiseaseData.java
> +    static Filter createFilter(String geomField, double x0, double y0, double x1, double y1,
We dont't need this

2020-07-24 18:41 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/DiseaseData.java
> +    Filter getSubsetFilter();
Don't need this. We only need to execute inserting operations. We are not going to use this model for querying

2020-07-24 18:41 UTC, Malintha1996 commented on src/main/java/io/datasearch/diseasedata/store/dengdipipeline/ingestion/data/DiseaseData.java
> +    List<Query> getTestQueries();
Don't need

2020-07-24 18:43 UTC, malinthar requested changes
Fix checkstyle issues and commented ones :)

2020-07-25 01:42 UTC, chanukaDissanayaka approved these changes

2020-07-26 02:31 UTC, chanukaDissanayaka approved these changes

2020-07-26 02:32 UTC, merged